function add_hover_to_lang_selection(){var timeoutVarLang;$('#lang','#top-bar').hover(function(){clearTimeout(timeoutVarLang);$(this).addClass('hover').addClass('white');$('#lang-detail','#top-bar').slideDown();},function(){$(this).removeClass('hover');timeoutVarLang=setTimeout(function(){if($('#lang-detail','#top-bar').hasClass('hover')===false&&($('.panel.combo-p').length==0||$('.panel.combo-p').is(':hidden'))){$('#lang-detail','#top-bar').fadeOut(0);$('#lang','#top-bar').removeClass('white');}},200);});$('#lang-detail','#top-bar').hover(function(){$(this).addClass('hover');},function(){$(this).removeClass('hover');timeoutVarLang=setTimeout(function(){if($('#lang','#top-bar').hasClass('hover')==false&&($('.panel.combo-p').length==0||$('.panel.combo-p').is(':hidden'))){$('#lang-detail','#top-bar').fadeOut(0);$('#lang','#top-bar').removeClass('white');}},200);});}
$('.submitBtn','#searchForm').click(function(e){e.preventDefault();$('#searchForm').submit();});$('#searchForm').submit(function(e){e.preventDefault();var search=$('#search','#searchForm');var $ckparam=$('#ckparam','#searchForm');var searchKey=$.trim(search.val());if(typeof pintrk!=="undefined"&&searchKey.length>1){pintrk('track','search',{search_query:searchKey});}
if(searchKey.length>1){if($ckparam.length){searchKey+="&"+$ckparam.val();}
location.href='/search/?q='+searchKey;}
return false;});$('#search','#searchForm').focus(function(){$(this).trigger('keyup');});$('#search','#searchForm').keydown(function(event){var keycode=(event.keyCode?event.keyCode:event.which);if(keycode=='13'){mdnsGTM.pushEvent("Header","Search","Search Press Enter");var search=$('#search','#searchForm');var searchKey=$.trim(search.val());var $ckparam=$('#ckparam','#searchForm');if(typeof pintrk!=="undefined"&&searchKey.length>1){pintrk('track','search',{search_query:searchKey});}
if($('#suggest-box','#header').is(':visible')&&suggestActiveRow!==null){location.href=suggestActiveRow.attr('href');}else{if(searchKey.length>1){if($ckparam.length){searchKey+="&"+$ckparam.val();}
location.href='/search/?q='+searchKey;}else if(searchKey.length==0&&search.data('keyword')!=undefined){location.href='/search/?q='+search.data('keyword');}}
return false;}});$('#search','#searchForm').keyup(function(event){var keycode=(event.keyCode?event.keyCode:event.which);var $this=$(event.currentTarget);var $suggestBox=$('#suggest-box','#header');if(keycode=='38'){if($suggestBox.is(':visible')){if(suggestActiveRow===null){suggestActiveRow=$('a:last-of-type',$suggestBox);}else{if(suggestActiveRow.is('a:first-of-type')===false){suggestActiveRow=suggestActiveRow.prev('a');}else{return;}}
$('a',$suggestBox).removeClass('active');suggestActiveRow.addClass('active');}}else if(keycode=='40'){if($suggestBox.is(':visible')){if(suggestActiveRow===null){suggestActiveRow=$('a:first-of-type',$suggestBox);}else{if(suggestActiveRow.is('a:last-of-type')===false){suggestActiveRow=suggestActiveRow.next('a');}else{return;}}
$('a',$suggestBox).removeClass('active');suggestActiveRow.addClass('active');}}else if(keycode=='13'){}else{var $autoCompleteClose=$('#autocomplete-close','#header');var searchText=$(this).val();if(searchText.length>2){$.getJSON('/api/suggest.php',{searchText:searchText}).done(function(obj){var items=[];$.each(obj.data,function(key,val){if(typeof val.name!=="undefined"&&typeof val.webUrl!=="undefined"){var akamaiKeyOrParam=akamaiParameter;if(val.webUrl.indexOf('?')===-1){akamaiKeyOrParam=akamaiKey;}
items.push('<a href="'+val.webUrl+akamaiKeyOrParam+'">'+val.name+'</a>');}});if(items.length>0){var suggestCekilisBanner=$('#suggest-box.cekilis');if(suggestCekilisBanner.length>0){$suggestBox.html('<a class="banner" href="'+suggestCekilisBanner.data('banner-link')+'"></a>');}else{$suggestBox.html('');}
$suggestBox.append(items.join('')).show();$this.addClass("newheaderfooter-search-borderRadius");$autoCompleteClose.show();}else{$suggestBox.empty().hide();$this.removeClass("newheaderfooter-search-borderRadius");$autoCompleteClose.hide();}
suggestActiveRow=null;});}else{$suggestBox.empty().hide();$this.removeClass("newheaderfooter-search-borderRadius");$autoCompleteClose.hide();}}});$('#autocomplete-close','#header').click(function(e){e.preventDefault();$('#search','#searchForm').val('').removeClass("newheaderfooter-search-borderRadius");$('#suggest-box','#header').empty().hide();$(this).hide();suggestActiveRow=null;});$('.close','#coupon-top-bar').click(function(){$('#coupon-top-bar').slideUp();$.cookie('coupon-bar-closed','1',{path:'/'});});var timeoutVarAcc;$('#account','#top-bar').hover(function(){clearTimeout(timeoutVarAcc);$(this).addClass('hover').addClass('white');$('#account-detail','#top-bar').slideDown();},function(){$(this).removeClass('hover');timeoutVarAcc=setTimeout(function(){if($('#account-detail','#top-bar').hasClass('hover')==false){$('#account-detail','#top-bar').fadeOut(0);$('#account','#top-bar').removeClass('white');}},200);});$('#account-detail','#top-bar').hover(function(){$(this).addClass('hover');},function(){$(this).removeClass('hover');timeoutVarAcc=setTimeout(function(){if($('#account','#top-bar').hasClass('hover')==false){$('#account-detail','#top-bar').fadeOut(0);$('#account','#top-bar').removeClass('white');}},200);});$(document).on("click",'#coupon-notifications-handler',function(e){var $this=$(e.currentTarget);var $obj=$("#coupon-notifications");var isOpen=$obj.hasClass('hover');var $detail=$("#coupon-notifications-list");$obj.addClass('hover');$detail.stop();if(!isOpen){var width;if($("body").hasClass("rtl")){width=$obj.offset().left-$(".top-bar-content").offset().left-30;}else{width=$(".top-bar-content").offset().left+960-$obj.offset().left-30;}
$detail.removeAttr("style");$detail.css({width:width}).slideDown();$this.addClass("newheaderfooter-notifications-open");mdnsGTM.pushEvent('Header','Bildirimler','click');}else{$detail.slideUp(function(){$detail.removeAttr("style");$obj.removeClass('hover');$this.removeClass("newheaderfooter-notifications-open");});}});$(document).on("click",function(e){if(!$(e.target).is('#coupon-notifications, #coupon-notifications *, #coupon-notifications-list, #coupon-notifications-list *')&&$('#coupon-notifications','#header').hasClass('hover')){$('#coupon-notifications-handler','#header').click();}});$("#header-menu .rootItem.hasSub").on("mouseenter",function(e){if($("#coupon-notifications").is(".hover")){$('#coupon-notifications-handler','#header').click();}});var timeoutVarBasket;$('#cart','#header').hover(function(){clearTimeout(timeoutVarBasket);$(this).addClass('hover').addClass('white');var cardDetailObj=$('#cart-detail','#header');cardDetailObj.slideDown();var eventSuffix;if(cardDetailObj.hasClass('group2')){eventSuffix='T';}else{eventSuffix='K';}},function(){$(this).removeClass('hover');timeoutVarBasket=setTimeout(function(){if($('#cart-detail','#header').hasClass('hover')==false){$('#cart-detail','#header').fadeOut(0);$('#cart','#header').removeClass('white');}},200);});$('#cart-detail','#header').hover(function(){$(this).addClass('hover');},function(){$(this).removeClass('hover');timeoutVarBasket=setTimeout(function(){if($('#cart','#header').hasClass('hover')==false){$('#cart-detail','#header').fadeOut(0);$('#cart','#header').removeClass('white');}},200);});$('.remove','#cart-detail').live('click',function(e){e.preventDefault();var id=$(this).data('id');var _deletedElement={'product_id':$(this).data('product-id'),'product_name':$(this).data('product-name'),'product_price':$(this).data('product-price')};$.ajax({url:''+(getCustomerLanguage())+'/api/basket_remove.php',data:{id:id},type:'POST',deletedElement:_deletedElement,success:function(o){if(o=='OK'){mdnsGTM.removeFromCart(this.deletedElement['product_id'],this.deletedElement['product_name'],'','',this.deletedElement['product_price'],'','',this.deletedElement['product_price']);}
updateBasketPopup(true);}});});$('.login-modal','#top-bar').colorbox({iframe:true,href:function(){return $(this).data('link');},width:693,height:502,scrolling:false,transition:'elastic',fastIframe:false,onLoad:function(){$('#cboxClose').remove();setTimeout(function(){if($('#layer').hasClass('right-side')){$('#modal-login-form-email').focus();}else{$('#modal-register-form-name').focus();}},500);}});add_hover_to_lang_selection();if($(".hasSub").length&&(typeof gPageType=='undefined'||gPageType!='checkout')){$(".hasSub").hover(subShow,subHide);}
function subShow(){$(".subMenu",this).addClass("open");$(this).addClass("hover");}
function subHide(){$(".subMenu",this).removeClass("open");$(this).removeClass("hover");}
function showCountryComboItems(action){var selectObj=$('#ship-country','#kargo_degistir');if(typeof action!=='undefined'&&action=='top'){$('.combo-panel > .combobox-item').addClass('display-none');$('option[data-visible="1"]',selectObj).each(function(){$('.combo-panel > .combobox-item:contains('+$(this).text()+')').removeClass('display-none');});}else{$('.combo-panel > .combobox-item').removeClass('display-none');$('.combo-panel > .combobox-item:last').addClass('display-none');var textboxObj=$('.textbox-text','#kargo_degistir');textboxObj.click();setTimeout(function(){textboxObj.click();},300);}}
$(document).ready(function(){(function(){var direction=$("body").hasClass("rtl")?"right":"left";$(".mainHeader","#header-menu").each(function(){var $title=$(this);var $detail=$title.next(".subMenu");if(!$detail.length){return;}
var directionValue=direction;var positionValue=Math.floor(direction==="left"?$title.position().left:(960-$title.position().left-$title.width()));$detail.css({width:"auto",left:"auto",right:"auto"});if(positionValue+$detail.outerWidth()>=958){directionValue=direction==="left"?"right":"left";positionValue=0;}
$detail.css(directionValue,positionValue+"px");});})();function fillCountryBox(){var responseData=[];akamaiKeyParameter='';if(akamaiKey!=='undefined'){akamaiKeyParameter=akamaiKey;}
var countryComboboxObj=$('#ship-country','#ship-country-form');var $footerCountry=$("#footer-country","#footer");if(countryComboboxObj.length>0){$.ajax({url:''+(getCustomerLanguage())+'/api/country_list.php'+akamaiKeyParameter+'',dataType:"JSON",success:function(response)
{responseData=response;render();}});function render()
{typeof countryComboboxObj.combobox==="function"&&countryComboboxObj.combobox({onLoadSuccess:function(){var countryList=countryComboboxObj.combobox('getData');$.each(countryList,function(index,value){countryComboboxObj.append($('<option></option>').attr('value',value.id).text(value.name));$footerCountry.append($('<option></option>').attr('value',value.id).text(value.name));var optionObj=$('option[value='+value.id+']',countryComboboxObj);var optionObj2=$('option[value='+value.id+']',$footerCountry);if(value.id!=1000){optionObj.attr('data-name-tags',value.name_tr+' '+value.name_en+' '+value.name_fr+' '+value.name_ar+' '+value.name_fa+' '+value.name_de+((value.name_tags?' '+value.name_tags:'')));optionObj2.attr('data-name-tags',value.name_tr+' '+value.name_en+' '+value.name_fr+' '+value.name_ar+' '+value.name_fa+' '+value.name_de+((value.name_tags?' '+value.name_tags:'')));}
if(value.selected){optionObj.attr('selected','selected');optionObj2.attr('selected','selected');}
if(value.visible){optionObj.attr('data-visible',1);optionObj2.attr('data-visible',1);}else{optionObj.attr('data-visible',0);optionObj2.attr('data-visible',0);}
if(value.id===1000){optionObj2.remove();}});showCountryComboItems('top');},data:responseData});}}}
fillCountryBox();if(typeof isUserDeleted!=='undefined'&&isUserDeleted){typeof transYourAccountDeleted!=='undefined'&&typeof transYourAccountDeletedMessage!=='undefined'&&typeof transOK!=='undefined'&&swal({title:transYourAccountDeleted,text:transYourAccountDeletedMessage,confirmButtonText:transOK});}
$("#cart-detail a:first-child:not(.btn-basket)","#header").click(function(){mdnsGTM.pushEvent("Header","Sepetim","Product Click");});});function getCustomerLanguage(){var url=window.location.href;var isLocal=false;var urlSlash=url.split('/');var urlDot=url.split('.');var mainUrl='';if(url.indexOf('local')!=-1){mainUrl=urlDot[0]+'.modanisa.com'}else{if(urlDot[0].indexOf('/dev')!=-1){var tmpPrefix=urlDot[0].replace(/\/deven|\/devfr|\/devde|\/devar|\/devfa/,'/dev');}else{var tmpPrefix=urlDot[0].replace(/\/en|\/fr|\/de|\/ar|\/fa|\/id/,'/');tmpPrefix+='www.';}
mainUrl=tmpPrefix+'.modanisa.com';}
if(urlDot.indexOf('en')!=-1||urlDot.indexOf('http://en')!=-1||urlDot.indexOf('http://deven')!=-1){mainUrl+='/en';}else if(urlDot.indexOf('fr')!=-1||urlDot.indexOf('http://fr')!=-1||urlDot.indexOf('http://devfr')!=-1){mainUrl+='/fr';}else if(urlDot.indexOf('de')!=-1||urlDot.indexOf('http://de')!=-1||urlDot.indexOf('http://devde')!=-1){mainUrl+='/de';}else if(urlDot.indexOf('ar')!=-1||urlDot.indexOf('http://ar')!=-1||urlDot.indexOf('http://devar')!=-1){mainUrl+='/ar';}else if(urlDot.indexOf('fa')!=-1||urlDot.indexOf('http://fa')!=-1||urlDot.indexOf('http://devfa')!=-1){mainUrl+='/fa';}else{mainUrl=urlSlash[0]+'//'+urlSlash[2];if(urlSlash[3]=='en'){mainUrl+='/en';}else if(urlSlash[3]=='fr'){mainUrl+='/fr';}else if(urlSlash[3]=='de'){mainUrl+='/de';}else if(urlSlash[3]=='fa'){mainUrl+='/fa';}else if(urlSlash[3]=='ar'){mainUrl+='/ar';}else if(urlSlash[3]=='id'){mainUrl+='/id';}}
return mainUrl;}
function updateBasketPopup(basketUpdated){basketUpdated=(!(typeof basketUpdated==='undefined'||basketUpdated===false));if(localStorage.getItem('basketItems')===null&&!basketUpdated){basketUpdated=true;}
if(basketUpdated&&typeof localStorage!=="undefined"&&localStorage!==null){$.getJSON('/api/basket_json.php').done(function(obj){try{localStorage.setItem('basketItems',JSON.stringify(obj));rebuildBasketPopUp();}catch(e){}});}else{rebuildBasketPopUp('created');}}
function rebuildBasketPopUp(rebuildStatus){if(typeof rebuildStatus==="undefined"){rebuildStatus=null;}
var cart=$('#cart');var cartDetail=$('#cart-detail');var basketItems=localStorage.getItem('basketItems');var cartDetailInner=$('.inner',cartDetail);if(basketItems==='[]'){cart.removeClass("newHeaderFooter-basket-active");cartDetailInner.addClass('display-none');$('.count',cart).text(0);$('.count',cartDetail).text("0");$('.total',cartDetail).text("");$('.btns',cartDetail).addClass('display-none');$('.no-item',cartDetail).removeClass('display-none');if($('body').hasClass('newHeaderFooter')){$('.head',cartDetail).addClass('display-none');$('.summary',cartDetail).addClass('display-none');}}else{cartDetailInner.html('');var obj=JSON.parse(basketItems);var content='';var itemCount=0;for(var i=0 in obj){var $item=obj[i];content+='<div class="row row-'+$item.id+'">';content+='<a href="'+$item.get_domain+'/'+$item.product_sef+'.html'+akamaiKey+'">';if(rebuildStatus=='created'){content+='<img border="0" class="lazy" src="//fns.modanisa.com/r/pro2/banner-upload/2018-10/modanisa-lazy-load.jpg" width="44" alt="'+$item.name+'" data-original="'+$item.pic+'" />';}else{content+='<img border="0" src="'+$item.pic+'" width="44" alt="'+$item.name+'" />';}
content+='<div class="detail">';content+='<div class="products-prices-wrapper">';if($item.campaignVariables){content+='<div class="products-prices">';if($item.campaignVariables.productFirstPrice){content+='<div class="price '+($item.campaignVariables.strikeOutFirstPrice?'price--strikeOut':'')+'"><bdi>'+$item.campaignVariables.productFirstPrice+'</bdi></div>';}
content+='</div>';if(typeof $item.campaignVariables.hideText!=='undefined'&&!$item.campaignVariables.hideText){content+='<div class="womens-day-badge" style="'+$item.campaignVariables.badgeStyle+'">'+$item.campaignVariables.badgeText+'<br></div>';}}else{content+='<div class="products-prices"><div class="price"><bdi>'+$item.sep_urun_fiyati_display+'</bdi></div></div>';}
content+='</div><!-- .products-prices-wrapper -->';content+='<div class="name-quantity">';if(typeof $item.brandName!=="undefined"){content+='<p class="brandName">'+$item.brandName+'</p>';}
content+='<p class="name">'+$item.name+'</p>';content+='<p class="quantity"><span class="code">'+$item.dil_sepet_urun_kodu+': '+$item.product_id+'</span> <span class="size">'+$item.p_option1_name+': '+$item.p_option1_value+'</span></p>';content+='</div><!-- .name-quantity -->';content+='</div><!-- .detail -->';content+='<div class="clear-both"></div>';content+='</a>';content+='<a title="'+$item.dil_sepet_sil+'" href="#" class="remove" data-id="'+$item.variant_id+'" data-product-id="'+$item['product_id']+'" data-product-name="'+$item['name']+'" data-product-price="'+$item['sep_urun_fiyati']+'"></a>';content+='</div>';itemCount+=1;}
cart.addClass("newHeaderFooter-basket-active");cartDetailInner.html(content).removeClass('display-none');$('.count',cart).text(itemCount);$('.no-item',cartDetail).addClass('display-none');$('.btns',cartDetail).removeClass('display-none');$('.count',cartDetail).text(itemCount);if($('body').hasClass('newHeaderFooter')){$('.head',cartDetail).removeClass('display-none');$('.summary',cartDetail).removeClass('display-none');}
if(typeof obj[0]!=="undefined"&&typeof obj[0].basketTotalPrice!=="undefined"){$('.total',cartDetail).text(obj[0].basketTotalPrice);}}}
$('.header-favorites','#header').click(function(){mdnsGTM.pushEvent('Header','Favorilerim','click');});$('#support','#top-bar').click(function(){mdnsGTM.pushEvent('Header','Satış Destek','click');});$('#cart','#header').click(function(){mdnsGTM.pushEvent('Header','Sepetim','click');});$('.btn-basket','#header').click(function(){mdnsGTM.pushEvent('Header','Sepetim','Sepetime Git');});$('.btn-checkout','#header').click(function(){mdnsGTM.pushEvent('Header','Sepetim','Şimdi Al');});$('#suggest-box','#header').click(function(){mdnsGTM.pushEvent('Header','Search','Suggest Box Click');});$('.mainHeader','#header-menu').click(function(){mdnsGTM.pushEvent('Navigasyon',$(this).text(),'Click');});$('.subMenu .item','#header-menu').click(function(){var action=$(this).text().trim();var label=$(this).parents('.rootItem').find('.mainHeader').text().trim();mdnsGTM.pushEvent('Navigasyon',action,label);});